### PR TITLE
$PWD is more reliable than CWD

### PR DESCRIPTION
**Pull request by ghost**
$PWD is not altered after calls to chdir() by the executable, though CWD is.

Also fixed a memory leak with realpath().

```
#include <stdio.h>
#include <unistd.h>

#include "getexecname.h"

int main() {
    printf("%s\n", getexecname());
    chdir("/");
    printf("%s\n", getexecname());
    return 0;
}
```

### CODE REVIEW

**Comment by ibara** [comment]
Your commit says you haven't tested it yet. Please let me know when you do.
Also, please style-ify:
```
if (condition) single_statement;
```
should be:
```
if (condition)
        single_statement;
```

**Comment by ghost** [comment]
Sorry, I've tested it now, and I verified it is working, forgot to clarify that. Fixing the styling as we speak.

**Comment by time-killer-games** [comment]
@ibara slightly off-topic, but it would be great if this were suggested to the OpenBSD team as an official API. With very little teaking, this could get the executable pathname of any process that doesn't modify its argv[] or related environment variables for security reasons. Thus allowing OpenBSD to have a KERN_PROC_PATHNAME implementation for sysctl() like FreeBSD, DragonFly and NetBSD already have, but without compensating on security because those who wish to hide their executable path may still do so. Since you are an OpenBSD committer, you'd have a bigger voice than I would. I'd pass this on to them.

**Comment by ghost** [comment]
I have written a sanity check to make sure the ino_t and dev_t match up between the associated process id and the path this function guesses is the executable path. Should I make another pull request adding this code?

You can test it yourself if you like. The code is added to my own API here:
https://github.com/time-killer-games/xproc/commit/03a643a7d33e679994f4896acfca7a9fa7d5467f

**Comment by ghost** [comment]
I can always close this if you don't want to accept my changes. It's fine either way. Just trying to help improve your code the best I can for your benefit. @ibara

**Pull request closed without merging**
